### ISSUE TITLE
not working for folder containing a german umlaut (ä,ö,ü)

### ISSUE THREAD

**Issue by rj-d2** [SpaceinvaderOne/Unraid_ZFS_Auto_Dataset_Update#6]
Hi,

thx for all your videos!! 
i tried the script, its working for most of my folders, but not on folders that have german umlauts in it (ä,ö,ü)
it renames the folder containing an umlaut  to ..._temp but does not create a dataset.

is there a way to get this working??

**Comment by SpaceinvaderOne** [comment]
Hi @rj-d2  Unfortunately its a limitation of ZFS for what can be in a dataset name. It is best to use ASCII characters only.  
I just tried manually creating a dataset and it failed

`root@BaseStar:~# zfs create sg1_storage/oneäöü`
`cannot create 'sg1_storage/oneäöü': invalid character '' in name`


However I have pushed a change to the script and added a function that will transliterate the German umlauts before creating datasets, replace German umlauts in folder names with ASCII approximations.  This would take a folder called oneäöü   and make a dataset called oneaou

Please try the new script and see if it helps your problem.

**Comment by SpaceinvaderOne** [comment]
Thats strange. I made a test trying to duplicate your folders and it worked for me

```
Checking if anything needs converting
Folders found that need converting.....continuing
Processing folder /mnt/sg1_storage/appdata_script/Erlösermittlungen...
Folder size: 394K
Creating and populating new dataset sg1_storage/appdata_script/Erloesermittlungen...
Validating copy...
Validation successful, cleanup can proceed.
Processing folder /mnt/sg1_storage/appdata_script/Gästehaus...
Folder size: 10K
Creating and populating new dataset sg1_storage/appdata_script/Gaestehaus...
Validating copy...
Validation successful, cleanup can proceed.
Processing folder /mnt/sg1_storage/appdata_script/Pässe...
Folder size: 1.3M
Creating and populating new dataset sg1_storage/appdata_script/Paesse...
Validating copy...
Validation successful, cleanup can proceed.
Skipping dataset /mnt/sg1_storage/appdata_script/container1...
Processing folder /mnt/sg1_storage/appdata_script/random_test...
Folder size: 1.0K
Creating and populating new dataset sg1_storage/appdata_script/random_test...
Validating copy...
Validation successful, cleanup can proceed.
The following folders were successfully converted to datasets:
/mnt/sg1_storage/appdata_script/Erlösermittlungen
/mnt/sg1_storage/appdata_script/Gästehaus
/mnt/sg1_storage/appdata_script/Pässe
/mnt/sg1_storage/appdata_script/random_test
Script Finished Sep 10, 2023 11:07.33

Full logs for this script are available at /tmp/user.scripts/tmpScripts/testscript/log.txt
```

After checking with folder or dataset script I see


```
**Datasets in sg1_storage/appdata_script are**
Erloesermittlungen
Gaestehaus
Paesse
container1
random_test

**Folders in sg1_storage/appdata_script are**
There are no folders
```

Please make sure you dont have dryrun set to yes as this would cause what you are seeing

**Comment by SpaceinvaderOne** [comment]
Thanks so uch for the beer @rj-d2 its very much appreciated :)
